# Generated by Django 2.1.1 on 2018-09-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Модель'),
        ),
    ]
