# Generated by Django 2.1.1 on 2018-09-19 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technics', '0002_auto_20180919_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipper',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technics.Model', verbose_name='Модель'),
        ),
    ]
